### ISSUE TITLE
Ignore some files or directory ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [artichoke/clang-format#55]
I tried to create a `.clang-format-ignore` in root directory but it seems to not work

Did I miss something ?

Thanks for this useful runner :)

**Comment by lopopolo** [comment]
I found [these docs](https://mesonbuild.com/Code-formatting.html) which seem to indicate that `.clang-format-ignore` is not part of `clang-format`. Instead it is part of [`run-clang-format.py`](https://github.com/Sarcasm/run-clang-format).

This is probably why this tool does not support it. I'd happily accept a PR which adds support.

**Comment by Nelson-numerical-software** [comment]
meson also use ".clang-format-ignore" file
https://mesonbuild.com/Code-formatting.html
(sorry, I am user of your package, currently no time to help your project.)

**Comment by lopopolo** [comment]
I've put up a PR for this here:

- https://github.com/artichoke/clang-format/pull/87

**Comment by lopopolo** [comment]
v0.16.0 is released with this feature. Thanks for the report and sorry it took so long for me to get to this.

I do feel this report pushed me to improve the quality of this package significantly. Thank you! 🙇
